name = "dns-filter-worker"
main = "worker.js"
compatibility_date = "2024-09-23"

[[kv_namespaces]]
binding = "RULES"
id = "c1274ab8f14b4dfcac2cd91af7bfda82"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true
